//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2FA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project2FA.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string AccountCodePageViewModelDeleteAccept {
            get {
                return ResourceManager.GetString("AccountCodePageViewModelDeleteAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string AccountCodePageViewModelDeleteCancel {
            get {
                return ResourceManager.GetString("AccountCodePageViewModelDeleteCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete this account irrevocably?.
        /// </summary>
        public static string AccountCodePageViewModelDeleteDescription {
            get {
                return ResourceManager.GetString("AccountCodePageViewModelDeleteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion.
        /// </summary>
        public static string AccountCodePageViewModelDeleteTitle {
            get {
                return ResourceManager.GetString("AccountCodePageViewModelDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to display name.
        /// </summary>
        public static string AccountLabel {
            get {
                return ResourceManager.GetString("AccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        public static string AccountUserName {
            get {
                return ResourceManager.GetString("AccountUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2fast.
        /// </summary>
        public static string Appname {
            get {
                return ResourceManager.GetString("Appname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyed!.
        /// </summary>
        public static string Copyed {
            get {
                return ResourceManager.GetString("Copyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit account.
        /// </summary>
        public static string EditAccountPageTitle {
            get {
                return ResourceManager.GetString("EditAccountPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No password.
        /// </summary>
        public static string NoPassword {
            get {
                return ResourceManager.GetString("NoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the existing datafile and enter the password..
        /// </summary>
        public static string UseDatafileLoadInfo {
            get {
                return ResourceManager.GetString("UseDatafileLoadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose datafile from path.
        /// </summary>
        public static string UseDatafileLocalPath {
            get {
                return ResourceManager.GetString("UseDatafileLocalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load datafile.
        /// </summary>
        public static string UseDatafileMainPrimaryButtonText {
            get {
                return ResourceManager.GetString("UseDatafileMainPrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load datafile.
        /// </summary>
        public static string UseDatafileMainTitle {
            get {
                return ResourceManager.GetString("UseDatafileMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UseDatafilePassword {
            get {
                return ResourceManager.GetString("UseDatafilePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        public static string UseDatafilePasswordRepeat {
            get {
                return ResourceManager.GetString("UseDatafilePasswordRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected filename:.
        /// </summary>
        public static string UseDatafileSelectedFilename {
            get {
                return ResourceManager.GetString("UseDatafileSelectedFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new datafile (first start).
        /// </summary>
        public static string WelcomePageCreateDatafile {
            get {
                return ResourceManager.GetString("WelcomePageCreateDatafile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First steps towards safety ....
        /// </summary>
        public static string WelcomePageFirstSteps {
            get {
                return ResourceManager.GetString("WelcomePageFirstSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!
        ///
        ///Start with another security factor in your daily life..
        /// </summary>
        public static string WelcomePageIntro {
            get {
                return ResourceManager.GetString("WelcomePageIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load existing datafile.
        /// </summary>
        public static string WelcomePageLoadDatafile {
            get {
                return ResourceManager.GetString("WelcomePageLoadDatafile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
